In [1]:
import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('shuffled_data.csv')
df

Email               Name  Gender   10th board  \
0        ishika_kapoor91@gmail.com      Ishika Kapoor  Female         ICSE   
1        arpita_biswas29@gmail.com      Arpita Biswas  Female         ICSE   
2          gopal_mahto11@gmail.com        Gopal Mahto    Male         CBSE   
3        anupama_verma63@gmail.com      Anupama Verma  Female         CBSE   
4    ishani_srivastava88@gmail.com  Ishani Srivastava  Female         ICSE   
..                             ...                ...     ...          ...   
395   anupama_mazumdar80@gmail.com   Anupama Mazumdar  Female  State Board   
396          its.amitb77@gmail.com      Amit Banerjee    Male        WBBSE   
397     nishant_mandal90@gmail.com     Nishant Mandal    Male         ICSE   
398   nikhil_kumar_rai87@gmail.com   Nikhil Kumar Rai    Male         CBSE   
399    naira_singhania72@gmail.com    Naira Singhania  Female        WBBSE   

     10th marks         12th board  12th marks  \
0          99.3                ISE        73.8   
1          73.0             WBCHSE        72.8   
2          80.7  Other state Board        76.1   
3          82.4  Other state Board        72.3   
4          91.7               CBSE        68.9   
..          ...                ...         ...   
395        72.4               CBSE        67.6   
396        90.0             WBCHSE        89.0   
397        99.8                ISE        80.8   
398        79.8               CBSE        88.8   
399        98.5             WBCHSE        69.8   

                                        Stream  Cgpa Internships(Y/N)  \
0                     Computer Science in AIML  7.56               No   
1                       Electrical Engineering  8.35               No   
2                     Computer Science in AIML  7.51              Yes   
3             Computer Science and Engineering  7.59              Yes   
4                  Computer Science and Design  8.34               No   
..                                         ...   ...              ...   
395                          Civil Engineering  8.12               No   
396           Computer Science and Engineering  8.60               No   
397           Computer Science in Data Science  8.26              Yes   
398  Electronics and Communication Engineering  9.07              Yes   
399           Computer Science and Engineering  8.47               No   

    Training(Y/N) Backlog in 5th sem Project(Y/N)  Communication level  \
0             Yes                 No          Yes                    3   
1              No                 No           No                    4   
2              No                Yes          Yes                    1   
3              No                 No          Yes                    3   
4             Yes                 No           No                    2   
..            ...                ...          ...                  ...   
395            No                 No           No                    4   
396            No                Yes          Yes                    2   
397            No                 No          Yes                    3   
398           Yes                 No          Yes                    5   
399            No                 No          Yes                    2   

    Technical Course(Y/N) Placement(Y/N)?  
0                     Yes          Placed  
1                     Yes          Placed  
2                     Yes      Not Placed  
3                     Yes          Placed  
4                      No      Not Placed  
..                    ...             ...  
395                   Yes      Not Placed  
396                   Yes      Not Placed  
397                   Yes          Placed  
398                   Yes          Placed  
399                   Yes      Not Placed  

[400 rows x 16 columns]

In [3]:
df.shape

(400, 16)

In [4]:
df.size

6400

In [5]:
df['Placement(Y/N)?'].value_counts()

Placed        248
Not Placed    152
Name: Placement(Y/N)?, dtype: int64

In [6]:
df.dtypes

Email                     object
Name                      object
Gender                    object
10th board                object
10th marks               float64
12th board                object
12th marks               float64
Stream                    object
Cgpa                     float64
Internships(Y/N)          object
Training(Y/N)             object
Backlog in 5th sem        object
Project(Y/N)              object
Communication level        int64
Technical Course(Y/N)     object
Placement(Y/N)?           object
dtype: object

In [7]:
df.isna().sum()

Email                    0
Name                     0
Gender                   0
10th board               0
10th marks               0
12th board               0
12th marks               0
Stream                   0
Cgpa                     0
Internships(Y/N)         0
Training(Y/N)            0
Backlog in 5th sem       0
Project(Y/N)             0
Communication level      0
Technical Course(Y/N)    0
Placement(Y/N)?          0
dtype: int64

In [8]:
df1=df.copy()
df1.drop(['Email','Name'], axis=1, inplace=True)

In [9]:
df1

Gender   10th board  10th marks         12th board  12th marks  \
0    Female         ICSE        99.3                ISE        73.8   
1    Female         ICSE        73.0             WBCHSE        72.8   
2      Male         CBSE        80.7  Other state Board        76.1   
3    Female         CBSE        82.4  Other state Board        72.3   
4    Female         ICSE        91.7               CBSE        68.9   
..      ...          ...         ...                ...         ...   
395  Female  State Board        72.4               CBSE        67.6   
396    Male        WBBSE        90.0             WBCHSE        89.0   
397    Male         ICSE        99.8                ISE        80.8   
398    Male         CBSE        79.8               CBSE        88.8   
399  Female        WBBSE        98.5             WBCHSE        69.8   

                                        Stream  Cgpa Internships(Y/N)  \
0                     Computer Science in AIML  7.56               No   
1                       Electrical Engineering  8.35               No   
2                     Computer Science in AIML  7.51              Yes   
3             Computer Science and Engineering  7.59              Yes   
4                  Computer Science and Design  8.34               No   
..                                         ...   ...              ...   
395                          Civil Engineering  8.12               No   
396           Computer Science and Engineering  8.60               No   
397           Computer Science in Data Science  8.26              Yes   
398  Electronics and Communication Engineering  9.07              Yes   
399           Computer Science and Engineering  8.47               No   

    Training(Y/N) Backlog in 5th sem Project(Y/N)  Communication level  \
0             Yes                 No          Yes                    3   
1              No                 No           No                    4   
2              No                Yes          Yes                    1   
3              No                 No          Yes                    3   
4             Yes                 No           No                    2   
..            ...                ...          ...                  ...   
395            No                 No           No                    4   
396            No                Yes          Yes                    2   
397            No                 No          Yes                    3   
398           Yes                 No          Yes                    5   
399            No                 No          Yes                    2   

    Technical Course(Y/N) Placement(Y/N)?  
0                     Yes          Placed  
1                     Yes          Placed  
2                     Yes      Not Placed  
3                     Yes          Placed  
4                      No      Not Placed  
..                    ...             ...  
395                   Yes      Not Placed  
396                   Yes      Not Placed  
397                   Yes          Placed  
398                   Yes          Placed  
399                   Yes      Not Placed  

[400 rows x 14 columns]

In [10]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
lst=['Gender','10th board','12th board','Stream', 'Internships(Y/N)', 
     'Training(Y/N)', 'Backlog in 5th sem', 'Project(Y/N)', 
     'Communication level', 'Technical Course(Y/N)', 'Placement(Y/N)?']
for i in lst:
    df1[i]=le.fit_transform(df1[i])
    
df1

Gender  10th board  10th marks  12th board  12th marks  Stream  Cgpa  \
0         0           1        99.3           1        73.8       4  7.56   
1         0           1        73.0           3        72.8       6  8.35   
2         1           0        80.7           2        76.1       4  7.51   
3         0           0        82.4           2        72.3       3  7.59   
4         0           1        91.7           0        68.9       2  8.34   
..      ...         ...         ...         ...         ...     ...   ...   
395       0           2        72.4           0        67.6       1  8.12   
396       1           3        90.0           3        89.0       3  8.60   
397       1           1        99.8           1        80.8       5  8.26   
398       1           0        79.8           0        88.8       8  9.07   
399       0           3        98.5           3        69.8       3  8.47   

     Internships(Y/N)  Training(Y/N)  Backlog in 5th sem  Project(Y/N)  \
0                   0              1                   0             1   
1                   0              0                   0             0   
2                   1              0                   1             1   
3                   1              0                   0             1   
4                   0              1                   0             0   
..                ...            ...                 ...           ...   
395                 0              0                   0             0   
396                 0              0                   1             1   
397                 1              0                   0             1   
398                 1              1                   0             1   
399                 0              0                   0             1   

     Communication level  Technical Course(Y/N)  Placement(Y/N)?  
0                      2                      1                1  
1                      3                      1                1  
2                      0                      1                0  
3                      2                      1                1  
4                      1                      0                0  
..                   ...                    ...              ...  
395                    3                      1                0  
396                    1                      1                0  
397                    2                      1                1  
398                    4                      1                1  
399                    1                      1                0  

[400 rows x 14 columns]

In [12]:
df1.dtypes

Gender                     int32
10th board                 int32
10th marks               float64
12th board                 int32
12th marks               float64
Stream                     int32
Cgpa                     float64
Internships(Y/N)           int32
Training(Y/N)              int32
Backlog in 5th sem         int32
Project(Y/N)               int32
Communication level        int64
Technical Course(Y/N)      int32
Placement(Y/N)?            int32
dtype: object

In [13]:
X=df1.iloc[:,:13]
y=df1.iloc[:,-1]


In [14]:
print(X)

     Gender  10th board  10th marks  12th board  12th marks  Stream  Cgpa  \
0         0           1        99.3           1        73.8       4  7.56   
1         0           1        73.0           3        72.8       6  8.35   
2         1           0        80.7           2        76.1       4  7.51   
3         0           0        82.4           2        72.3       3  7.59   
4         0           1        91.7           0        68.9       2  8.34   
..      ...         ...         ...         ...         ...     ...   ...   
395       0           2        72.4           0        67.6       1  8.12   
396       1           3        90.0           3        89.0       3  8.60   
397       1           1        99.8           1        80.8       5  8.26   
398       1           0        79.8           0        88.8       8  9.07   
399       0           3        98.5           3        69.8       3  8.47   

     Internships(Y/N)  Training(Y/N)  Backlog in 5th sem  Project(Y/N)  \
0

In [15]:
#scaling the dataset using Min-Max scaler
from sklearn.preprocessing import MinMaxScaler
ms=MinMaxScaler()
X_sc=ms.fit_transform(X)
X_sc

array([[0.        , 0.33333333, 0.99087591, ..., 1.        , 0.5       ,
        1.        ],
       [0.        , 0.33333333, 0.51094891, ..., 0.        , 0.75      ,
        1.        ],
       [1.        , 0.        , 0.65145985, ..., 1.        , 0.        ,
        1.        ],
       ...,
       [1.        , 0.33333333, 1.        , ..., 1.        , 0.5       ,
        1.        ],
       [1.        , 0.        , 0.6350365 , ..., 1.        , 1.        ,
        1.        ],
       [0.        , 1.        , 0.97627737, ..., 1.        , 0.25      ,
        1.        ]])

In [16]:
#splitting the dataset to train data and test data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_sc,y,test_size=0.2,random_state=1)

## AdaBoost Classifier

In [17]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import ConfusionMatrixDisplay,classification_report

ad=AdaBoostClassifier()
ad.fit(X_train,y_train)
y_pred1=ad.predict(X_test)
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.96      0.82      0.89        33
           1       0.88      0.98      0.93        47

    accuracy                           0.91        80
   macro avg       0.92      0.90      0.91        80
weighted avg       0.92      0.91      0.91        80



## Logistic Regression Classifier

In [18]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(random_state=0, solver='lbfgs', max_iter=1000).fit(X_train, y_train)
# printing the acc
y_pred2=clf.predict(X_test)
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       0.95      0.58      0.72        33
           1       0.77      0.98      0.86        47

    accuracy                           0.81        80
   macro avg       0.86      0.78      0.79        80
weighted avg       0.84      0.81      0.80        80



## Support Vector Classifier

In [19]:
from sklearn.svm import SVC

svc=SVC()
svc.fit(X_train,y_train)
y_pred3=svc.predict(X_test)
print(classification_report(y_test,y_pred3))

              precision    recall  f1-score   support

           0       0.92      0.67      0.77        33
           1       0.80      0.96      0.87        47

    accuracy                           0.84        80
   macro avg       0.86      0.81      0.82        80
weighted avg       0.85      0.84      0.83        80



## Naive Bayes Classifier

In [20]:
from sklearn.naive_bayes import GaussianNB

nb=GaussianNB()
nb.fit(X_train,y_train)
y_pred4=nb.predict(X_test)
print(classification_report(y_test,y_pred4))

              precision    recall  f1-score   support

           0       0.93      0.79      0.85        33
           1       0.87      0.96      0.91        47

    accuracy                           0.89        80
   macro avg       0.90      0.87      0.88        80
weighted avg       0.89      0.89      0.89        80



## Gradient Boosting Classifier

In [21]:
from sklearn.ensemble import GradientBoostingClassifier

gb=GradientBoostingClassifier()
gb.fit(X_train,y_train)
y_pred5=gb.predict(X_test)
print(classification_report(y_test,y_pred5))

              precision    recall  f1-score   support

           0       0.97      0.94      0.95        33
           1       0.96      0.98      0.97        47

    accuracy                           0.96        80
   macro avg       0.96      0.96      0.96        80
weighted avg       0.96      0.96      0.96        80



In [60]:
y_pred2

array([1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1])

In [61]:
from sklearn.metrics import confusion_matrix

In [62]:
confusion_matrix(y_test,y_pred1)

array([[27,  6],
       [ 1, 46]], dtype=int64)

In [81]:
confusion_matrix(y_test,y_pred2)

array([[27,  6],
       [ 1, 46]], dtype=int64)

In [64]:
confusion_matrix(y_test,y_pred3)

array([[22, 11],
       [ 2, 45]], dtype=int64)

In [65]:
confusion_matrix(y_test,y_pred4)

array([[26,  7],
       [ 2, 45]], dtype=int64)

In [69]:
from sklearn.model_selection import cross_val_score
# Perform cross-validation with 5 folds (you can adjust the 'cv' parameter)
scores = cross_val_score(gb, X, y, cv=5) 

print("Cross-Validation Scores:", scores)
print("Average Cross-Validation Score:", scores.mean())


Cross-Validation Scores: [0.8875 0.9125 0.9375 0.8625 0.85  ]
Average Cross-Validation Score: 0.8899999999999999


In [34]:
import numpy as np

# Assuming X_test is a NumPy array and gb is a trained Gradient Boosting model
test_input = X_test[20]  # Accessing the 50th row from X_test
predicted_proba = gb.predict_proba(np.array(test_input).reshape(1, -1))
predicted_proba2 = clf.predict_proba(np.array(test_input).reshape(1, -1))
print(predicted_proba)
print(predicted_proba2)


[[0.45559993 0.54440007]]
[[0.73036409 0.26963591]]


In [87]:
with open('scaler.pkl', 'wb') as scaler_file:
    pickle.dump(ms, scaler_file)

In [67]:
# Save the trained model to a file using pickle
with open('abhikf1.pickle', 'wb') as model_file:
    pickle.dump(clf, model_file)

